### ISSUE TITLE
Mesh dependence: Vertex visibility computation

### ISSUE THREAD

**Issue by MiraPurkrabek** [MiraPurkrabek/RePoGen#12]
Hi @MiraPurkrabek , 
Thank you very much for your answer, 
but after solving the above problem I have encountered a new problem, which is as follows.
Generating poses and views...
  0%|                                                                                                                                       | 0/2 [00:00<?, ?it/s]DRI3 not available
failed to load driver: zink
  0%|                                                                                                                                       | 0/2 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "scripts/sample_random_poses.py", line 785, in <module>
    main(args)
  File "scripts/sample_random_poses.py", line 388, in main
    visibilities = msh.vertex_visibility(
  File "/home/m11002163/.conda/envs/mesh/lib/python3.8/site-packages/psbody/mesh/mesh.py", line 284, in vertex_visibility
    vis, n_dot_cam = self.vertex_visibility_and_normals(camera, omni_directional_camera)
  File "/home/m11002163/.conda/envs/mesh/lib/python3.8/site-packages/psbody/mesh/mesh.py", line 295, in vertex_visibility_and_normals
    'cams': np.array([camera.origin.flatten()])}
AttributeError: 'list' object has no attribute 'origin'
This looks like a problem in the mesh?
About the mesh installation, I am following https://github.com/MPI-IS/mesh/tree/master
After I run the test on that page, it shows no problem.
What could be the problem?
Thank you in advance.

_Originally posted by @EWE002 in https://github.com/MiraPurkrabek/RePoGen/issues/11#issuecomment-1943221267_

**Comment by MiraPurkrabek** [comment]
OK, I believe I found the bug  @EWE002 .
I forgot that I'm using my fork of the MPI-IS/mesh repository. I did various changes there but the one that hinders your code will be on line 341 of file _mesh.py_ ([link](https://github.com/MiraPurkrabek/mesh/blob/e12c88ed1b7dd5622dbcc75a2472943bd64745d0/mesh/mesh.py#L341)). There are three quick solutions, please choose which suits you the best.

1. Install psbody.mesh library from my fork - [https://github.com/MiraPurkrabek/mesh](https://github.com/MiraPurkrabek/mesh)
2. Edit the linked lines in your installation of the psbody.mesh (requires you to install from source as in the option 1.)
3. Edit the RePoGen code such that the variable _camera\_position_ has attribute _origin_ that will give you value of the array. You can refer to this [StackOverflow question](https://stackoverflow.com/questions/67509913/add-an-attribute-to-a-numpy-array-in-runtime) for inspiration.

I edited the README to recommend the first solution. Please let me know if solved the bug.

**Comment by EWE002** [comment]
Thank you so much for your answer!
After I ran the first option according to your instructions, the composite image was generated correctly!
But there is another small concern, after I installed psbody according to your fork, 
I ran $make tests to make sure the installation was successful
But it shows a problem :
![image](https://github.com/MiraPurkrabek/RePoGen/assets/100507360/471d1043-96c3-4957-ba5d-5e0eb5f8e2d9)

**Comment by MiraPurkrabek** [comment]
Great to hear that the RePoGen generation works well!

I tried the tests and got the same error even though the RePoGen generation works fine. 

The _visibility_ source needs to be loaded correctly. It is defined in a C++ file in /mesh/src/py_visibility.cpp. It may be a general problem or connected only to unit tests and their loading since the error does not influence the RePoGen code.
Since it does not break our code, I must assign it a low priority and postpone it until later.
